version: '3'
services:
  mysql:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: akaunting_root_password
      MYSQL_DATABASE: akaunting_db
      MYSQL_USER: akaunting_admin
      MYSQL_PASSWORD: akaunting_password
    volumes:
      - ./var/docker-volumes/mysql:/var/lib/mysql
  web:
    image: akaunting
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    environment:
      APP_DEBUG: "true"
    links:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: akaunting_root_password
      PMA_HOST: db
      PMA_PORT: 3306
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
